dependencies:
- name: exposecontroller
  version: 2.3.89
  repository: http://chartmuseum.jenkins-x.io
  alias: expose
- name: exposecontroller
  version: 2.3.89
  repository: http://chartmuseum.jenkins-x.io
  alias: cleanup
- name: cloudbees-core
  version: 3.4.0
  repository: https://charts.cloudbees.com/public/cloudbees
  alias: cbcore
