dependencies:
- alias: cbcore
  name: cloudbees-core
  repository: https://charts.cloudbees.com/public/cloudbees
  version: 3.4.1
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: spring-boot-1
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
